name: guide_me
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  rive: ^0.13.20
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.0
  pin_code_fields: ^8.0.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.7
  logger: ^2.5.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  mailer: ^6.4.1
  ulid: ^2.0.1
  cloud_functions: ^5.4.0
  random_string: ^2.3.1
  carousel_slider: ^5.0.0
  fl_chart: ^0.71.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  firebase_storage: ^12.4.5
  universal_platform: ^1.1.0
  path: ^1.9.1
  provider: ^6.1.4
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  badges: ^3.1.2
  flutter_map: ^8.1.1
  rxdart: ^0.28.0
  giphy_get: ^3.6.1
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.3
  midtrans_sdk: ^1.0.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - mailersend-proxy/.env